"""LLM layer for narrative explanations.

This module never performs financial calculations. It only explains the
deterministic output generated by the finance service.
"""

from __future__ import annotations

import json
from typing import Any

import httpx

from app.core.config import settings
from app.models import PlanData


def _build_fallback_explanation(payload: dict[str, Any]) -> str:
    """Create a deterministic fallback explanation when LLM is unavailable."""

    allocation = payload.get("allocation", {})
    sip = payload.get("monthly_sip", 0)
    corpus = payload.get("projected_corpus", 0)
    expected_return = payload.get("expected_return_annual", 0)

    return (
        f"Recommended monthly SIP is {sip:.2f}. "
        f"Suggested allocation is Equity {allocation.get('equity', 0)}%, "
        f"Debt {allocation.get('debt', 0)}%, Liquid {allocation.get('liquid', 0)}%. "
        f"Projected corpus at plan horizon is {corpus:.2f} with an expected annual return of "
        f"{expected_return * 100:.2f}%."
    )


def _call_openrouter(messages: list[dict[str, str]], fallback: str) -> str:
    """Call OpenRouter for narrative text generation with deterministic fallback."""

    if not settings.openrouter_api_key:
        return fallback

    headers = {
        "Authorization": f"Bearer {settings.openrouter_api_key}",
        "Content-Type": "application/json",
    }
    if settings.openrouter_site_url:
        headers["HTTP-Referer"] = settings.openrouter_site_url
    if settings.openrouter_site_name:
        headers["X-Title"] = settings.openrouter_site_name

    body = {
        "model": settings.openrouter_model,
        "messages": messages,
        "temperature": 0.2,
        "max_tokens": 180,
    }

    with httpx.Client(timeout=8.0) as client:
        response = client.post(
            f"{settings.openrouter_base_url}/chat/completions",
            headers=headers,
            json=body,
        )
        response.raise_for_status()
        data = response.json()
        content = data["choices"][0]["message"]["content"]
        return str(content).strip() if content else fallback


def generate_explanation(plan_json: PlanData | dict) -> str:
    """Generate JSON-safe explanation using OpenRouter with safe fallback."""

    payload = plan_json.model_dump() if hasattr(plan_json, "model_dump") else plan_json
    fallback = _build_fallback_explanation(payload)

    prompt = (
        "You are a finance explainer. Explain the provided deterministic plan in under 90 words. "
        "Do not perform new calculations. Do not add numbers not present in input. "
        "Return only plain text."
    )
    messages = [
        {"role": "system", "content": prompt},
        {"role": "user", "content": json.dumps(payload)},
    ]

    try:
        explanation = _call_openrouter(messages, fallback)
    except Exception:
        explanation = fallback

    # Ensure the string remains JSON-safe for transport.
    return json.dumps(explanation)[1:-1]


def _build_fallback_scenario_summary(
    baseline_payload: dict[str, Any],
    updated_payload: dict[str, Any],
    delta_payload: dict[str, Any],
) -> str:
    """Deterministic scenario summary used when OpenRouter is unavailable."""

    sip_base = baseline_payload.get("monthly_sip", 0)
    sip_new = updated_payload.get("monthly_sip", 0)
    corpus_base = baseline_payload.get("projected_corpus", 0)
    corpus_new = updated_payload.get("projected_corpus", 0)
    timeline_delta = delta_payload.get("horizon_delta_years", 0)

    return (
        f"What-if scenario updates SIP from {sip_base:.2f} to {sip_new:.2f}. "
        f"Projected corpus changes from {corpus_base:.2f} to {corpus_new:.2f}. "
        f"Timeline delta is {timeline_delta:+d} years."
    )


def generate_scenario_summary(
    baseline_plan: PlanData | dict,
    updated_plan: PlanData | dict,
    delta: dict[str, Any],
) -> str:
    """Generate OpenRouter-backed what-if summary without performing calculations."""

    baseline_payload = baseline_plan.model_dump() if hasattr(baseline_plan, "model_dump") else baseline_plan
    updated_payload = updated_plan.model_dump() if hasattr(updated_plan, "model_dump") else updated_plan
    delta_payload = delta

    fallback = _build_fallback_scenario_summary(baseline_payload, updated_payload, delta_payload)

    prompt = (
        "You are a personal-finance explainer. Summarize the what-if impact in 1 short sentence. "
        "Use only numbers provided in the JSON input. Do not perform any extra calculations. "
        "Return plain text only."
    )
    messages = [
        {"role": "system", "content": prompt},
        {
            "role": "user",
            "content": json.dumps(
                {
                    "baseline_plan": baseline_payload,
                    "updated_plan": updated_payload,
                    "delta": delta_payload,
                }
            ),
        },
    ]

    try:
        summary = _call_openrouter(messages, fallback)
    except Exception:
        summary = fallback

    return json.dumps(summary)[1:-1]


def _build_fallback_behavior_observations(flags: list[str]) -> list[str]:
    """Deterministic fallback coaching lines from behavior flags."""

    mapping = {
        "Low savings rate detected": "You are saving less than 20% of income. Increase savings gradually to protect long-term goals.",
        "High spending risk": "Your expenses are close to income. Reduce discretionary spending to avoid cashflow stress.",
        "No existing investments found": "You have no active investments yet. Start with a consistent SIP to build momentum.",
        "Debt pressure is elevated": "Debt level is high for current income. Prioritize repayment before taking higher investment risk.",
        "Healthy financial behavior pattern": "Your behavior looks stable. Maintain consistency and review progress monthly.",
    }
    return [mapping.get(flag, flag) for flag in flags[:3]]


def _format_inr(amount: Any) -> str:
    try:
        return f"INR {float(amount):,.0f}"
    except (TypeError, ValueError):
        return "INR 0"


def generate_behavioral_observations(flags: list[str], profile: dict[str, Any]) -> list[str]:
    """Generate coaching observations from deterministic behavioral flags only."""

    income = profile.get("monthly_income", 0)
    expenses = profile.get("monthly_expenses", 0)
    debt = profile.get("debt_outstanding", 0)
    horizon = profile.get("investment_horizon_years", 0)
    risk = str(profile.get("risk_appetite", "moderate")).capitalize()
    existing_count = len(profile.get("existing_investments", []) or [])

    fallback = [
        (
            f"With {_format_inr(income)} income and {_format_inr(expenses)} expenses, "
            "your monthly room for investing is limited. Protect SIP consistency before increasing risk."
        ),
        (
            f"Your debt is {_format_inr(debt)} and horizon is {horizon} years. "
            "Prioritize stable cashflow first so compounding is not interrupted."
        ),
        (
            f"Your risk profile is {risk} with {existing_count} active investments. "
            "Diversification matters more than chasing short-term return spikes."
        ),
    ] if flags else _build_fallback_behavior_observations(flags)

    prompt = (
        "You are an empathetic financial coach. Convert behavioral flags into 2-3 short, actionable observations. "
        "Each observation must include at least one concrete value from profile context (income/expenses/debt/horizon/risk). "
        "Do not do any calculations. Use only the given flags and profile context. "
        "Return only a JSON array of strings."
    )
    messages = [
        {"role": "system", "content": prompt},
        {
            "role": "user",
            "content": json.dumps({"behavioral_flags": flags, "profile": profile}),
        },
    ]

    try:
        content = _call_openrouter(messages, json.dumps(fallback))
        parsed = json.loads(content)
        if isinstance(parsed, list) and all(isinstance(item, str) for item in parsed):
            return parsed[:3]
    except Exception:
        pass

    return fallback

